server.servlet.context-path=/orders
server.port=9020

# DB Configuration
spring.datasource.url=jdbc:postgresql://${DB_SERVICE:order-service}:5432/${DB_NAME:order-db}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

my.variable=order-github-default
features.user-tracking-enabled=false